<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    public static function getDescription($profile)
    {
        $descriptions = [
            'PROFILO CIOCCOLATO' => 'Intenso, caldo e avvolgente, ma anche freddo come nel gusto del gelato. Dark come quello fondente, ma anche delicato come quello al latte. Si coniuga perfettamente con molti cibi esaltandone il gusto, fonde note di sapore e le trasforma in armonia.<br><br><strong>Perché viene considerato afrodisiaco? </strong><br>Il cioccolato contiene feniletilamina, una sostanza che stimola il circuito dopaminergico cerebrale al rilascio di endorfine, generando una sensazione di piacere. Per questo il cioccolato è considerato la coccola per antonomasia per il palato e la mente dei golosi e non solo, infatti per qualcuno è addirittura un antidepressivo naturale.<br><br><strong>Che amante sei? </strong>Se sei un cioccolato sei ecclettico, generoso e plasmabile, sai essere dolce, amaro e persino salato. Prediligi l\'armonia, per questo pratichi una sessualità tradizionale, ma con il partner o la partner giusta ti spinge ad esperienze più ardite. Il tuo punto di forza è la capacita di saper intuire i desideri e le fantasie romantiche e soddisfare gli istinti più passionali. Insomma un amante attento e sapiente a cui non occorre chiedere. II difetto? II "cioccolato" può causare dipendenza, per questo è importante imparare a dosarsi senza esagerare.<br><br><strong>Suggerimento: </strong>l\'attenzione al partner è un punto di forza, ma snaturarti ti potrebbe allontanare del piacere.',
            'PROFILO VANIGLIA' => 'La vaniglia è una spezia dolce e aromatica che dà frutti commestibili. Ne esistono di diverse provenienze, quasi tutte esotiche. Ingrediente principe di ricette sensuali, di pasticceri raffinati e profumieri ispirati.<br><br><strong>Perché viene considerata afrodisiaca?</strong><br>Le proprietà afrodisiache della vaniglia sono note sin da tempi remoti. Già gli Aztechi la usavano come afrodisiaco mescolandola al cioccolato. Nel 700 si affermò come alimento eccitante e diventò nota per le sue proprietà stimolanti.<br>Agli inizi del Novecento lo psicanalista e sessuologo Havelock Ellis scopri che i lavoratori delle piantagioni di vaniglia vivevano in uno stato di continua eccitazione sessuale per via del profumo diffuso nell\'aria e delle polveri che penetravano nei loro pori della pelle. Un "effetto collaterale" (coronato peraltro da numerosa prole) della malattia professionale chiamata vanillismo.<br><br><strong>Che amante sei? </strong>Se sei una vaniglia sei l\'emblema della seduzione. Raffinata elegante, sensuale, mai volgare, talvolta inarrivabile, preziosa, sai tormentare e sconvolgere i sensi. Se non esageri sei l\'amante perfetta per chi ama il gioco della seduzione, per alimentare il desiderio nell\'attesa di concedersi. Il meglio di te lo dai un\'attività sessuale che inizia come rilassante e calmante, e gradatamente diventa esplosiva, proprio come nel Tantra.<br> Il difetto? Non sei per tutti perché ami un corteggiamento paziente e attento.<br><br><strong>Suggerimento: </strong>farsi rincorrere è un gioco divertente, ma esagerare è frustrante e rischia di lasciare a mani vuote!',
            'PROFILO PEPERONCINO' => 'Bacca piccante del genere di piante Capsicum. Caldo infuocato, sa accendere anche il "piatto più mite". E un frutto affascinante che ha giocato un ruolo importante in molte culture, non solo come spezia culinaria, ma anche come afrodisiaco. Il peperoncino piccante viene consumato quotidianamente da circa un quarto della popolazione mondiale.<br><br><strong>Perché viene considerato afrodisiaco? </strong><br>Il peperoncino contiene la capsaicina, sostanza ad effetto stimolante e vasodilatatore, favorisce la circolazione sanguigna e facilita l\'afflusso di sangue anche nella zona peniena (ormone VIP - Vasoactive Intestinal Polypeptide).<br><br><strong>Che amante sei? </strong>Se sei un peperoncino, sei carisma, fuoco e trasgressione. Ami prendere iniziative sempre nuove, dai il meglio nelle relazioni mordi e fuggi o con chi ama lasciarsi tentare e guidare. Non disdegni i rapporti multipli e le esperienze originali. Sei un ottimo antidoto contro la routine e la noia, amante ideale per chi cerca esperienze piccanti. Il difetto? Non ami i corteggiamenti, ti annoiano, e neppure i legami duraturi, che invece ti spaventano. Come tutte le passioni forti c\'è il rischio che si affievoliscono velocemente.<br><br><strong>Suggerimento: </strong>a letto vuoi tutto e subito, attenzione rischi di bruciarti un\'occasione che ha bisogno di un po\' di tempo per carburare prima di lasciarsi andare.',
        ];

        return $descriptions[$profile] ?? '';
    }
}