<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    public static function getDescription($profile)
    {
        $descriptions = [
            'PROFILO CIOCCOLATO' => 'Intenso, caldo e avvolgente, ma anche freddo come nel gusto del gelato. <i>Dark</i> come quello fondente, ma anche delicato come quello al latte. Si coniuga perfettamente con molti aromi esaltandone il gusto, fonde note di sapore e le trasforma in armonia.<br><br><strong>Perché viene considerato afrodisiaco?</strong><br> Il cioccolato contiene feniletilamina (PEA), una sostanza che stimola il circuito dopaminergico cerebrale del piacere al rilascio di endorfine, generando una sensazione di piacere. Per questo il cioccolato è considerato la coccola per antonomasia per il palato e la mente dei più golosi e non solo, per qualcuno addirittura un antidepressivo naturale.<br><strong>L\'amante cioccolato </strong>è eclettico, generoso e plasmabile, sa essere dolce, amaro e persino salato. Predilige l\'armonia, per questo pratica una sessualità tradizionale, ma con il partner o la partner giusta si spinge ad esperienze più ardite. Punto di forza è la capacita di saper intuire i desideri e le fantasie romantiche e soddisfare gli istinti più passionali. Insomma un amante attento e sapiente a cui non occorre chiedere.<br><strong>II difetto? </strong>II "cioccolato" può causare dipendenza, per questo è importante "dosarlo" nella giusta quantità senza esagerare.<br><br><strong>COLORE NERO</strong><br><strong>PUNTO DI FORZA NELLA SEDUZIONE: </strong>i preliminari<br><strong>AFFINITÀ CON ALTRI PROFILI: </strong>visto il carattere eclettico del cioccolato, è un buon connubio sia con peperoncino che con vaniglia, con cioccolato può essere interessante, ma a volte <i>too much</i>',
            'PROFILO VANIGLIA' => 'La vaniglia è una spezia dolce e aromatica che dà frutti commestibili. Ne esistono di diverse provenienze, quasi tutte esotiche. Ingrediente principe di ricette sensuali, di pasticceri raffinati e profumieri ispirati.<br><br><strong>Perché viene considerata afrodisiaca?</strong><br> Le proprietà afrodisiache della vaniglia sono note sin da tempi remoti. Già gli Aztechi la usavano come afrodisiaco mescolandola al cioccolato. Nel 700 si affermò come alimento eccitante e diventò nota per le sue proprietà stimolanti.<br> Agli inizi del Novecento lo psicanalista e sessuologo Havelock Ellis scoprì che i lavoratori delle piantagioni di vaniglia vivevano in uno stato di continua eccitazione sessuale per via del profumo diffuso nell\'aria e delle polveri che penetravano nei loro pori della pelle. Un "effetto collaterale" (coronato peraltro da numerosa prole) della malattia professionale chiamata <i>vanuismg.</i><br><strong>L\'amante vaniglia </strong>è l\'emblema della seduzione. Raffinata elegante, sensuale, mai volgare, talvolta inarrivabile preziosa, l\'amante vaniglia tormenta e sconvolge i sensi. Se ben dosata la vaniglia è l\'amante perfetta, il meglio di sé lo dà un\'attività sessuale che inizia come rilassante e calmante, e gradatamente esplosiva.<br><strong>Il difetto? </strong>Non è per tutti perché richiede un corteggiamento paziente e attento.<br><br><strong>COLORE ORO</strong><br><strong>PUNTO DI FORZA NELLA SEDUZIONE: </strong>il corteggiamento<br><strong>AFFINITÀ: </strong>la vaniglia esalta il cioccolato, meno il peperoncino a causa di una incompatibilità sui tempi e sui modi usati per sedurre. Con un\'altra vaniglia ottima intese sui gusti, ma c\'è il rischio di rincorrersi senza incontrarsi mai.',
            'PROFILO PEPERONCINO' => 'Bacca piccante del genere di piante <i>Capsicum</i>. Caldo infuocato, sa accendere anche il "piatto più mite". È un frutto affascinante che ha giocato un ruolo importante in molte culture, non solo come spezia culinaria, ma anche come afrodisiaco. Il peperoncino piccante viene consumato quotidianamente da circa un quarto della popolazione mondiale.<br><br><strong>Perché viene considerato afrodisiaco?</strong><br> Il peperoncino contiene la capsaicina, sostanza ad effetto stimolante e vasodilatatore, favorisce la circolazione sanguigna e facilita l\'afflusso di sangue anche nella zona peniena (ormone <i>VIP - Vasoactive Intestinal Polypeptide</i>).<br> L\'amante peperoncino è carisma, fuoco, trasgressione. Ama prendere iniziative sempre nuove, dà il meglio nelle relazioni mordi e fuggi e con chi ama lasciarsi tentare e guidare. A letto vuole tutto e subito, non disdegna i rapporti multipli e le esperienze originali. Ottimo antidoto contro la routine e la noia, amante ideale se si cercano esperienze piccanti.<br> </strong>Il difetto? </strong>Non ama i corteggiamenti, lo annoiano, e neppure i legami duraturi, che invece lo spaventano. Come tutte le passioni forti c\'è il rischio che si affievoliscono velocemente.<br><br><strong>COLORE ROSSO</strong><br><strong>PUNTO DI FORZA NELLA SEDUZIONE: </strong>la passione<br><strong>AFFINITÀ: </strong>con il cioccolato un buon connubio, meno con la vaniglia a causa di una incompatibilità sui tempi e sui modi usati per sedurre. Con un altro peperoncino ci si intende senza freni, ma attenzione perché troppo <i>hot</i> rischia di bruciare',
        ];

        return $descriptions[$profile] ?? '';
    }
}